# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(943, 754)
        self.list1 = QtWidgets.QListWidget(Form)
        self.list1.setGeometry(QtCore.QRect(290, 90, 91, 191))
        self.list1.setObjectName("list1")
        item = QtWidgets.QListWidgetItem()
        self.list1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list1.addItem(item)
        self.list2 = QtWidgets.QListWidget(Form)
        self.list2.setGeometry(QtCore.QRect(390, 90, 141, 191))
        self.list2.setObjectName("list2")
        self.com1 = QtWidgets.QComboBox(Form)
        self.com1.setGeometry(QtCore.QRect(30, 50, 87, 22))
        self.com1.setObjectName("com1")
        self.com1.addItem("")
        self.com1.addItem("")
        self.com2 = QtWidgets.QComboBox(Form)
        self.com2.setGeometry(QtCore.QRect(190, 40, 87, 22))
        self.com2.setObjectName("com2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(860, 130, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.list3 = QtWidgets.QListWidget(Form)
        self.list3.setGeometry(QtCore.QRect(540, 90, 291, 191))
        self.list3.setObjectName("list3")
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setGeometry(QtCore.QRect(770, 350, 93, 28))
        self.btn1.setObjectName("btn1")
        self.list_page_items = QtWidgets.QListWidget(Form)
        self.list_page_items.setGeometry(QtCore.QRect(20, 380, 121, 192))
        self.list_page_items.setObjectName("list_page_items")
        item = QtWidgets.QListWidgetItem()
        self.list_page_items.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_page_items.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_page_items.addItem(item)
        self.list_tab_items = QtWidgets.QListWidget(Form)
        self.list_tab_items.setGeometry(QtCore.QRect(150, 380, 141, 192))
        self.list_tab_items.setObjectName("list_tab_items")
        self.list_operate_items = QtWidgets.QListWidget(Form)
        self.list_operate_items.setGeometry(QtCore.QRect(300, 380, 111, 192))
        self.list_operate_items.setObjectName("list_operate_items")
        item = QtWidgets.QListWidgetItem()
        self.list_operate_items.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_operate_items.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list_operate_items.addItem(item)
        self.list_element_toolbar_items = QtWidgets.QListWidget(Form)
        self.list_element_toolbar_items.setGeometry(QtCore.QRect(430, 380, 141, 81))
        self.list_element_toolbar_items.setObjectName("list_element_toolbar_items")
        self.list_finally_items = QtWidgets.QListWidget(Form)
        self.list_finally_items.setGeometry(QtCore.QRect(610, 380, 256, 192))
        self.list_finally_items.setObjectName("list_finally_items")
        self.list_element_items = QtWidgets.QListWidget(Form)
        self.list_element_items.setGeometry(QtCore.QRect(430, 460, 141, 111))
        self.list_element_items.setObjectName("list_element_items")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        __sortingEnabled = self.list1.isSortingEnabled()
        self.list1.setSortingEnabled(False)
        item = self.list1.item(0)
        item.setText(_translate("Form", "ToolBar"))
        item = self.list1.item(1)
        item.setText(_translate("Form", "TabBar"))
        item = self.list1.item(2)
        item.setText(_translate("Form", "btn"))
        item = self.list1.item(3)
        item.setText(_translate("Form", "input"))
        item = self.list1.item(4)
        item.setText(_translate("Form", "文本获取"))
        self.list1.setSortingEnabled(__sortingEnabled)
        self.com1.setItemText(0, _translate("Form", "工单"))
        self.com1.setItemText(1, _translate("Form", "工作票"))
        self.pushButton.setText(_translate("Form", "增加"))
        self.btn1.setText(_translate("Form", "开始"))
        __sortingEnabled = self.list_page_items.isSortingEnabled()
        self.list_page_items.setSortingEnabled(False)
        item = self.list_page_items.item(0)
        item.setText(_translate("Form", "工单"))
        item = self.list_page_items.item(1)
        item.setText(_translate("Form", "工作票"))
        item = self.list_page_items.item(2)
        item.setText(_translate("Form", "装置"))
        self.list_page_items.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.list_operate_items.isSortingEnabled()
        self.list_operate_items.setSortingEnabled(False)
        item = self.list_operate_items.item(0)
        item.setText(_translate("Form", "点击"))
        item = self.list_operate_items.item(1)
        item.setText(_translate("Form", "写入文本"))
        item = self.list_operate_items.item(2)
        item.setText(_translate("Form", "追加文本"))
        self.list_operate_items.setSortingEnabled(__sortingEnabled)
